Watching for file changes with StatReloader
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'api.ipify.org'. You may need to add 'api.ipify.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.ipify.org'. You may need to add 'api.ipify.org' to ALLOWED_HOSTS.
Bad Request: /http:/api.ipify.org/
Invalid HTTP_HOST header: 'www.shadowserver.org'. You may need to add 'www.shadowserver.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.shadowserver.org'. You may need to add 'www.shadowserver.org' to ALLOWED_HOSTS.
Bad Request: /www.shadowserver.org:443
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Bad Request: /api/islogged
Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Bad Request: /aaa9
Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Bad Request: /aab8
Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Bad Request: /boaform/admin/formLogin
Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Bad Request: /boaform/admin/formLogin
Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/backend/venv/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.36.65.236:8000'. You may need to add '3.36.65.236' to ALLOWED_HOSTS.
Bad Request: /
Watching for file changes with StatReloader
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
/home/ubuntu/backend/backend/schema.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
